title: "MetaFlux"
description: >
  MetaFlux: Meta-learning global carbon fluxes from sparse spatiotemporal observations
recipes:
  - id: "metaflux_daily"
    object: "recipe:METAFLUX_GPP_RECO_daily"
  - id: "metaflux_monthly"
    object: "recipe:METAFLUX_GPP_RECO_monthly"

maintainers:
  - name: "Julius Busecke"
    orcid: "0000-0001-8571-865X"
    github: jbusecke

provenance:
  providers:
    - name: "Zenodo"
      description: "Zenodo"
      roles:
        - host
      url: https://zenodo.org/record/7761881#.ZFv9OS-B30p
    - name: "Nathaniel et al."
      description: "Authors of MetaFlux: Meta-learning global carbon fluxes from sparse spatiotemporal observations"
      roles:
        - producer
        - licensor
  license: "CC-BY-4.0"